[target.thumbv8m.main-none-eabihf]

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

#runner = "./picotool/build/picotool load -u -v -x -t elf"
runner = 'probe-rs run --chip rp235x'

[build]
target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)

[env]
DEFMT_LOG = "debug"